services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ggs-app
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    working_dir: /var/www/html

  nginx:
    image: nginx:alpine
    container_name: ggs-nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db

  db:
    image: mysql:8
    container_name: mysql-db-ggs
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-ggs
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db-data: